<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RingsideItem extends Doctrine_Record
{

	public function setTableDefinition()
	{
		$this->setTableName('items');
		$this->hasColumn('item_id', 'string', 255, array('alltypes' => array(0 => 'string'), 'ntype' => 'varchar(255)', 'fixed' => false, 'values' => array(), 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
		$this->hasColumn('item_app_id', 'integer', 4, array('alltypes' => array(0 => 'integer'), 'ntype' => 'int(10) unsigned', 'unsigned' => 1, 'values' => array(), 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
		$this->hasColumn('item_data_type', 'integer', 4, array('alltypes' => array(0 => 'integer'), 'ntype' => 'int(10) unsigned', 'unsigned' => 1, 'values' => array(), 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
		$this->hasColumn('item_url', 'string', null, array('alltypes' => array(0 => 'string', 1 => 'clob'), 'ntype' => 'text', 'fixed' => false, 'values' => array(), 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
		$this->hasColumn('item_refurl', 'string', null, array('alltypes' => array(0 => 'string', 1 => 'clob'), 'ntype' => 'text', 'fixed' => false, 'values' => array(), 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
		$this->hasColumn('item_status', 'string', 1, array('alltypes' => array(0 => 'string', 1 => 'boolean'), 'ntype' => 'varchar(1)', 'fixed' => false, 'values' => array(), 'primary' => false, 'default' => 'A', 'notnull' => true, 'autoincrement' => false));
		$this->hasColumn('id', 'integer', 4, array('alltypes' => array(0 => 'integer'), 'ntype' => 'int(10) unsigned', 'unsigned' => 1, 'values' => array(), 'primary' => true, 'notnull' => true, 'autoincrement' => true));
		
		$this->index('unique', array('fields' => array('item_app_id', 'item_id', 'item_status'), 'type' => 'unique'));
	}

	public function setUp()
	{
		parent::setUp();
		$this->actAs('Timestampable', array('created' =>  array('name'    =>  'created',
                                                                'type'    =>  'timestamp',
                                                                'format'  =>  'Y-m-d H:i:s',
                                                                'disabled' => false,
                                                                'options' =>  array()),
                                            'updated' =>  array('name'    =>  'modified',
                                                                'type'    =>  'timestamp',
                                                                'format'  =>  'Y-m-d H:i:s',
                                                                'disabled' => false,
                                                                'options' =>  array())));
	}

}