<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RingsideAppKey extends Doctrine_Record
{
	public function setTableDefinition()
	{
		$this->setTableName('app_keys');

		$this->index('unique', array('fields' => array('app_id', 'network_id'), 'type' => 'unique'));
		
		$this->hasColumn('app_id', 'integer', 4, array('alltypes' => array(0 => 'integer'), 'ntype' => 'int(10) unsigned', 'unsigned' => 1, 'values' => array(), 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
		$this->hasColumn('network_id', 'string', 32, array('alltypes' => array(0 => 'string'), 'ntype' => 'varchar(32)', 'fixed' => false, 'values' => array(), 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
		$this->hasColumn('api_key', 'string', 32, array('alltypes' => array(0 => 'string'), 'ntype' => 'varchar(32)', 'fixed' => false, 'values' => array(), 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
		$this->hasColumn('secret', 'string', 32, array('alltypes' => array(0 => 'string'), 'ntype' => 'varchar(32)', 'fixed' => false, 'values' => array(), 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
		$this->hasColumn('id', 'integer', 4, array('alltypes' => array(0 => 'integer'), 'ntype' => 'int(10) unsigned', 'unsigned' => 1, 'values' => array(), 'primary' => true, 'notnull' => true, 'autoincrement' => true));		
		$this->hasColumn('key_id', 'integer');
	}

	public function setUp()
	{
		parent::setUp();
//		$this->hasOne('RingsideNetwork', array('local' => 'network_id', 'foreign' => 'id'));
		$this->hasOne('RingsideApp', array('local' => 'app_id', 'foreign' => 'id', 'onDelete' => 'CASCADE'));
		$this->actAs('Timestampable', array('created' =>  array('name'    =>  'created',
                                                                'type'    =>  'timestamp',
                                                                'format'  =>  'Y-m-d H:i:s',
                                                                'disabled' => false,
                                                                'options' =>  array()),
                                            'updated' =>  array('name'    =>  'modified',
                                                                'type'    =>  'timestamp',
                                                                'format'  =>  'Y-m-d H:i:s',
                                                                'disabled' => false,
                                                                'options' =>  array())));
	}
    

}

//UNIQUE KEY `unique_idx` USING BTREE (`app_id`,`network_id`,`user_id`)