<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RingsideFriend extends Doctrine_Record
{

	public function setTableDefinition()
	{
		$this->setTableName('friends');
		$this->hasColumn('from_id', 'string', 255);
		$this->hasColumn('to_id', 'string', 255);
		$this->hasColumn('domain_key', 'string', 255);
		$this->hasColumn('access', 'integer', 255);
		$this->hasColumn('status', 'integer', 255);
	}

	public function setUp()
	{
		parent::setUp();
		$this->actAs('Timestampable', array('created' =>  array('name'    =>  'created',
                                                                'type'    =>  'timestamp',
                                                                'format'  =>  'Y-m-d H:i:s',
                                                                'disabled' => false,
                                                                'options' =>  array()),
                                            'updated' =>  array('name'    =>  'modified',
                                                                'type'    =>  'timestamp',
                                                                'format'  =>  'Y-m-d H:i:s',
                                                                'disabled' => false,
                                                                'options' =>  array())));
	}
}