<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RingsideMailBox extends Doctrine_Record
{

	public function setTableDefinition()
	{
		$this->setTableName('mail_box');
		$this->hasColumn('mail_id', 'integer', 4, array('alltypes' => array(0 => 'integer'), 'ntype' => 'int(10) unsigned', 'unsigned' => 1, 'values' => array(), 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
		$this->hasColumn('uid', 'integer', 4, array('alltypes' => array(0 => 'integer'), 'ntype' => 'int(10) unsigned', 'unsigned' => 1, 'values' => array(), 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
		$this->hasColumn('deleted', 'integer', 1, array('alltypes' => array(0 => 'integer', 1 => 'boolean'), 'ntype' => 'tinyint(1)', 'unsigned' => 0, 'values' => array(), 'primary' => false, 'default' => '0', 'notnull' => true, 'autoincrement' => false));
		$this->hasColumn('last_opened', 'timestamp', null, array('alltypes' => array(0 => 'timestamp'), 'ntype' => 'timestamp', 'values' => array(), 'primary' => false, 'default' => 'CURRENT_TIMESTAMP', 'notnull' => true, 'autoincrement' => false));
		$this->hasColumn('id', 'integer', 4, array('alltypes' => array(0 => 'integer'), 'ntype' => 'int(10) unsigned', 'unsigned' => 1, 'values' => array(), 'primary' => true, 'notnull' => true, 'autoincrement' => true));
	
		$this->index('unique', array('fields' => array('mail_id', 'uid'), 'type' => 'unique'));
	}

	public function setUp()
	{
		parent::setUp();
		$this->hasMany('RingsideMailMessage', array('local' => 'mail_id', 'foreign' => 'mail_id'));
		$this->hasOne('RingsideMail', array('local' => 'mail_id', 'foreign' => 'mail_id'));
		$this->actAs('Timestampable', array('created' =>  array('name'    =>  'created',
                                                                'type'    =>  'timestamp',
                                                                'format'  =>  'Y-m-d H:i:s',
                                                                'disabled' => false,
                                                                'options' =>  array()),
                                            'updated' =>  array('name'    =>  'modified',
                                                                'type'    =>  'timestamp',
                                                                'format'  =>  'Y-m-d H:i:s',
                                                                'disabled' => false,
                                                                'options' =>  array())));
	}
}


