<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RingsideUser extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('users');
        $this->hasColumn('id', 'integer', 4, array('alltypes' => array(0 => 'integer'), 'ntype' => 'int(10) unsigned', 'unsigned' => 1, 'values' => array(), 'primary' => true, 'notnull' => true, 'autoincrement' => true));
        $this->hasColumn('username', 'string', 255, array('alltypes' => array(0 => 'string'), 'ntype' => 'varchar(45)', 'fixed' => false, 'values' => array(), 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
        $this->hasColumn('domain_id', 'integer');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('RingsideDomain as domain', array('local' => 'domain_id', 'foreign' => 'id'));
        $this->hasOne('RingsideCredential as credential', array('local' => 'id', 'foreign' => 'user_id', 'onDelete' => 'CASCADE'));
        $this->hasMany('RingsideApp as DeveloperApp', array('local' => 'id',
                                      'foreign' => 'app_id',
                                      'refClass' => 'RingsideDeveloperApp'));
        $this->hasMany('RingsideApp as UserApp', array('local' => 'id',
                                      'foreign' => 'app_id',
                                      'refClass' => 'RingsideUsersApp'));

        $this->actAs('Timestampable', array('created' =>  array('name'    =>  'created',
                                                                'type'    =>  'timestamp',
                                                                'format'  =>  'Y-m-d H:i:s',
                                                                'disabled' => false,
                                                                'options' =>  array()),
                                            'updated' =>  array('name'    =>  'modified',
                                                                'type'    =>  'timestamp',
                                                                'format'  =>  'Y-m-d H:i:s',
                                                                'disabled' => false,
                                                                'options' =>  array())));
    }
}