<?php
require_once('ringside/api/dao/tables/RingsidePrincipalTable.php');

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RingsidePrincipal extends Doctrine_Record
{

	public function setTableDefinition()
	{
		$this->setTableName('principal');
		$this->hasColumn('id', 'integer', 4, array('alltypes' => array(0 => 'integer'), 'ntype' => 'int(10) unsigned', 'unsigned' => 1, 'values' => array(), 'primary' => true, 'notnull' => true, 'autoincrement' => true));
		//    $this->hasColumn('app_id', 'integer', 4, array('alltypes' =>  array(  0 => 'integer', ), 'ntype' => 'int(10) unsigned', 'unsigned' => 1, 'values' =>  array(), 'primary' => true, 'notnull' => true, 'autoincrement' => true));
	}

	public function setUp()
	{
		parent::setUp();
		$this->hasMany('RingsidePrincipalMap', array('local' => 'id', 'foreign' => 'principal_id', 'onDelete' => 'CASCADE'));
		$this->actAs('Timestampable', array('created' =>  array('name'    =>  'created',
                                                                'type'    =>  'timestamp',
                                                                'format'  =>  'Y-m-d H:i:s',
                                                                'disabled' => false,
                                                                'options' =>  array()),
                                            'updated' =>  array('name'    =>  'modified',
                                                                'type'    =>  'timestamp',
                                                                'format'  =>  'Y-m-d H:i:s',
                                                                'disabled' => false,
                                                                'options' =>  array())));
	}

}