<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RingsideUsersProfileEcontact extends Doctrine_Record
{

	public function setTableDefinition()
	{
		$this->setTableName('users_profile_econtact');
		$this->hasColumn('id', 'integer', 4, array('alltypes' => array(0 => 'integer'), 'ntype' => 'int(10) unsigned', 'unsigned' => 1, 'values' => array(), 'primary' => true, 'notnull' => true, 'autoincrement' => true));
		$this->hasColumn('user_id', 'integer', 4, array('alltypes' => array(0 => 'integer'), 'ntype' => 'int(10) unsigned', 'unsigned' => 1, 'values' => array(), 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
		$this->hasColumn('contact_type', 'enum', 12, array('alltypes' => array(0 => 'enum', 1 => 'integer'), 'ntype' => 'enum(\'email\',\'AIM\',\'Google Talk\',\'Skype\',\'Windows Live\',\'Yahoo\',\'Gadu-Gadu\',\'ICQ\')', 'fixed' => false, 'values' => array(0 => 'email', 1 => 'AIM', 2 => 'Google Talk', 3 => 'Skype', 4 => 'Windows Live', 5 => 'Yahoo', 6 => 'Gadu-Gadu', 7 => 'ICQ'), 'primary' => false, 'notnull' => false, 'autoincrement' => false));
		$this->hasColumn('contact_value', 'string', 100, array('alltypes' => array(0 => 'string'), 'ntype' => 'varchar(100)', 'fixed' => false, 'values' => array(), 'primary' => false, 'notnull' => false, 'autoincrement' => false));
	}

	public function setUp()
	{
		parent::setUp();
		$this->actAs('Timestampable', array('created' =>  array('name'    =>  'created',
                                                                'type'    =>  'timestamp',
                                                                'format'  =>  'Y-m-d H:i:s',
                                                                'disabled' => false,
                                                                'options' =>  array()),
                                            'updated' =>  array('name'    =>  'modified',
                                                                'type'    =>  'timestamp',
                                                                'format'  =>  'Y-m-d H:i:s',
                                                                'disabled' => false,
                                                                'options' =>  array())));
	}

}