<?php

require_once 'ringside/api/dao/records/RingsideUsersProfile.php';

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RingsideUsersProEcontact extends Doctrine_Record
{

  public function setTableDefinition()
  {
    $this->setTableName('users_pro_econtact');
    $this->hasColumn('id', 'integer', 4, array('alltypes' =>  array(  0 => 'integer', ), 'ntype' => 'int(10) unsigned', 'unsigned' => 1, 'values' =>  array(), 'primary' => true, 'notnull' => true, 'autoincrement' => true));
    $this->hasColumn('profile_id', 'integer', 4, array('alltypes' =>  array(  0 => 'integer', ), 'ntype' => 'int(10) unsigned', 'unsigned' => 1, 'values' =>  array(), 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
    $this->hasColumn('contact_type', 'string', 100, array('alltypes' =>  array(  0 => 'string', ), 'ntype' => 'varchar(100)', 'fixed' => false, 'values' =>  array(), 'primary' => false, 'notnull' => false, 'autoincrement' => false));
    $this->hasColumn('contact_value', 'string', 100, array('alltypes' =>  array(  0 => 'string', ), 'ntype' => 'varchar(100)', 'fixed' => false, 'values' =>  array(), 'primary' => false, 'notnull' => false, 'autoincrement' => false));
  }

  public function setUp()
  {
    parent::setUp();
    $this->hasOne('RingsideUsersProfile', array('local' => 'profile_id', 'foreign' => 'id'));
  }

}