<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RingsidePaymentPlan extends Doctrine_Record
{

	public function setTableDefinition()
	{
		$this->setTableName('PaymentPlans');
		$this->hasColumn('id', 'integer', 4, array('alltypes' => array(0 => 'integer'), 'ntype' => 'int(10) unsigned', 'unsigned' => 1, 'values' => array(), 'primary' => true, 'notnull' => true, 'autoincrement' => true));
		$this->hasColumn('aid', 'integer', 4, array('alltypes' => array(0 => 'integer'), 'ntype' => 'int(10) unsigned', 'unsigned' => 1, 'values' => array(), 'primary' => false, 'notnull' => false, 'autoincrement' => false));
		$this->hasColumn('network_id', 'integer', 4, array('alltypes' => array(0 => 'integer'), 'ntype' => 'int(10) unsigned', 'unsigned' => 1, 'values' => array(), 'primary' => false, 'notnull' => false, 'autoincrement' => false));
		$this->hasColumn('name', 'string', null, array('alltypes' => array(0 => 'string', 1 => 'clob'), 'ntype' => 'text', 'fixed' => false, 'values' => array(), 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
		$this->hasColumn('length', 'integer', 4, array('alltypes' => array(0 => 'integer'), 'ntype' => 'int(3)', 'unsigned' => 0, 'values' => array(), 'primary' => false, 'default' => '12', 'notnull' => true, 'autoincrement' => false));
		$this->hasColumn('unit', 'string', 6, array('alltypes' => array(0 => 'string'), 'ntype' => 'varchar(6)', 'fixed' => false, 'values' => array(), 'primary' => false, 'default' => 'months', 'notnull' => true, 'autoincrement' => false));
		$this->hasColumn('price', 'float', null, array('alltypes' => array(0 => 'float'), 'ntype' => 'float', 'unsigned' => 0, 'values' => array(), 'primary' => false, 'default' => '', 'notnull' => true, 'autoincrement' => false));
		$this->hasColumn('description', 'string', 255, array('alltypes' => array(0 => 'string'), 'ntype' => 'varchar(255)', 'fixed' => false, 'values' => array(), 'primary' => false, 'notnull' => false, 'autoincrement' => false));
	}

	public function setUp()
	{
		parent::setUp();
		$this->actAs('Timestampable', array('created' =>  array('name'    =>  'created',
                                                                'type'    =>  'timestamp',
                                                                'format'  =>  'Y-m-d H:i:s',
                                                                'disabled' => false,
                                                                'options' =>  array()),
                                            'updated' =>  array('name'    =>  'modified',
                                                                'type'    =>  'timestamp',
                                                                'format'  =>  'Y-m-d H:i:s',
                                                                'disabled' => false,
                                                                'options' =>  array())));
	}

}