<fb:tabs>  
	<fb:tab-item href='edit.php' title='Basic' <?php if($page==1) { print("selected='true'"); }?>	/>  
	<fb:tab-item href='contact.php' title='Contact' <?php if($page==2) { print("selected='true'"); }?>/>  
	<fb:tab-item href='relationships.php' title='Relationships' <?php if($page==3) { print("selected='true'"); }?>/>  
	<fb:tab-item href='personal.php' title='Personal' <?php if($page==4) { print("selected='true'"); }?>/>  
	<fb:tab-item href='education.php' title='Education' <?php if($page==5) { print("selected='true'"); }?>/> 
	<fb:tab-item href='work.php' title='Work' <?php if($page==6) { print("selected='true'"); }?>/>  
	<fb:tab-item href='picture.php' title='Picture' <?php if($page==7) { print("selected='true'"); }?>/>  
</fb:tabs>
