<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RingsidePrincipalMapTable extends Doctrine_Table
{
    const PRINCIPAL_MAP_CLASS = 'RingsidePrincipalMap';

    public function findOneBySubject($app_id, $network, $uid)
    {
        $query =	Doctrine_Query::create()
        ->from(self::PRINCIPAL_MAP_CLASS)
        ->where('app_id = ? AND network_id = ? AND uid = ?', array($app_id, $network, $uid));
        return $query->execute()->getFirst();
    }

    public function findByIdForApp($app_id, $principal_id)
    {
        $query =	Doctrine_Query::create()
        ->from(self::PRINCIPAL_MAP_CLASS)
        ->where('app_id = ? AND principal_id = ?', array($app_id, $principal_id));
        return $query->execute();
    }
    
    public function findBySubject($app_id, $network, $uid)
    {
        // TODO: I was really hoping to use innerJoin, but it's not clear how to using Doctrine
        $query =	Doctrine_Query::create()
        ->select('p1.*')
        ->from(self::PRINCIPAL_MAP_CLASS.' p1, '.self::PRINCIPAL_MAP_CLASS.' p2')
        ->where('p2.principal_id = p1.principal_id AND p2.app_id = ? AND p2.network_id = ? AND p2.uid = ?');
        return $query->execute(array($app_id, $network, $uid));
    }
    
    public function findOneByNetwork($app_id, $network_id, $principal_id)
    {
        $query =	Doctrine_Query::create()
        ->from(self::PRINCIPAL_MAP_CLASS)
        ->where('app_id = ? AND network_id = ? AND id = ?', array($app_id, $network_id, $principal_id));
        $result = $query->execute();
        return $result->getFirst();
    }

    public function findByNetwork($app_id, $network_id, array $principal_ids)
    {
        $query =	Doctrine_Query::create()
        ->from(self::PRINCIPAL_MAP_CLASS)
        ->where('app_id = ? AND network_id = ?', array($app_id, $network_id))
        ->whereIn('principal_id', $principal_ids);
        return $query->execute();
    }

    public function findBySubjectForNetwork($app_id, $network_id, array $uids)
    {
        $query = Doctrine_Query::create()
        ->from(self::PRINCIPAL_MAP_CLASS)
        ->where('app_id = ? AND network_id = ?', array($app_id, $network_id))
        ->whereIn('uid', $uids);
        return $query->execute();
    }
}